/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/portfolio/AboutSection.vue')['default']
    AnimatedAvatar: typeof import('./components/shared/AnimatedAvatar.vue')['default']
    ChartRenderer: typeof import('./components/result/ChartRenderer.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./components/chat/ChatMessage.vue')['default']
    ChatSection: typeof import('./components/portfolio/ChatSection.vue')['default']
    ChatWidget: typeof import('./components/chat/ChatWidget.vue')['default']
    ExperienceSection: typeof import('./components/portfolio/ExperienceSection.vue')['default']
    MouseSpotlight: typeof import('./components/portfolio/MouseSpotlight.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCode: typeof import('naive-ui')['NCode']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    ProjectsSection: typeof import('./components/portfolio/ProjectsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeading: typeof import('./components/portfolio/SectionHeading.vue')['default']
    SiteFooter: typeof import('./components/portfolio/SiteFooter.vue')['default']
    SiteSidebar: typeof import('./components/portfolio/SiteSidebar.vue')['default']
  }
}
